export const ADD_CONDITION = "condition/ADD_CONDITION";
export const ADD_CONDITION_SUCCESS = "condition/ADD_CONDITION_SUCCESS";
export const ADD_CONDITION_FAILURE = "condition/ADD_CONDITION_FAILURE";

export const GET_CONDITION_LIST = "condition/GET_CONDITION_LIST";
export const GET_CONDITION_LIST_SUCCESS = "condition/GET_CONDITION_LIST_SUCCESS";
export const GET_CONDITION_LIST_FAILURE = "condition/GET_CONDITION_LIST_FAILURE";

export const UPDATE_CONDITION = "condition/UPDATE_CONDITION";
export const UPDATE_CONDITION_SUCCESS = "condition/UPDATE_CONDITION_SUCCESS";
export const UPDATE_CONDITION_FAILURE = "condition/UPDATE_CONDITION_FAILURE";

export const DELETE_CONDITION = "condition/DELETE_CONDITION";
export const DELETE_CONDITION_SUCCESS = "condition/DELETE_CONDITION_SUCCESS";
export const DELETE_CONDITION_FAILURE = "condition/DELETE_CONDITION_FAILURE";

export const GET_CONDITION = "condition/GET_CONDITION";
export const GET_CONDITION_SUCCESS = "condition/GET_CONDITION_SUCCESS";
export const GET_CONDITION_FAILURE = "condition/GET_CONDITION_FAILURE";

