export const ADD_CATEGORY = "category/ADD_CATEGORY";
export const ADD_CATEGORY_SUCCESS = "category/ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "category/ADD_CATEGORY_FAILURE";

export const GET_CATEGORY_LIST = "category/GET_CATEGORY_LIST";
export const GET_CATEGORY_LIST_SUCCESS = "category/GET_CATEGORY_LIST_SUCCESS";
export const GET_CATEGORY_LIST_FAILURE = "category/GET_CATEGORY_LIST_FAILURE";

export const UPDATE_CATEGORY = "category/UPDATE_CATEGORY";
export const UPDATE_CATEGORY_SUCCESS = "category/UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILURE = "category/UPDATE_CATEGORY_FAILURE";

export const DELETE_CATEGORY = "category/DELETE_CATEGORY";
export const DELETE_CATEGORY_SUCCESS = "category/DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "category/DELETE_CATEGORY_FAILURE";

export const GET_CATEGORY = "category/GET_CATEGORY";
export const GET_CATEGORY_SUCCESS = "category/GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILURE = "category/GET_CATEGORY_FAILURE";
