export const ADD_PAYMENT = "payment/ADD_PAYMENT";
export const ADD_PAYMENT_SUCCESS = "payment/ADD_PAYMENT_SUCCESS";
export const ADD_PAYMENT_FAILURE = "payment/ADD_PAYMENT_FAILURE";

export const GET_PAYMENT_LIST = "payment/GET_PAYMENT_LIST";
export const GET_PAYMENT_LIST_SUCCESS = "payment/GET_PAYMENT_LIST_SUCCESS";
export const GET_PAYMENT_LIST_FAILURE = "payment/GET_PAYMENT_LIST_FAILURE";

export const UPDATE_PAYMENT = "payment/UPDATE_PAYMENT";
export const UPDATE_PAYMENT_SUCCESS = "payment/UPDATE_PAYMENT_SUCCESS";
export const UPDATE_PAYMENT_FAILURE = "payment/UPDATE_PAYMENT_FAILURE";

export const DELETE_PAYMENT = "payment/DELETE_PAYMENT";
export const DELETE_PAYMENT_SUCCESS = "payment/DELETE_PAYMENT_SUCCESS";
export const DELETE_PAYMENT_FAILURE = "payment/DELETE_PAYMENT_FAILURE";

export const GET_PAYMENT = "payment/GET_PAYMENT";
export const GET_PAYMENT_SUCCESS = "payment/GET_PAYMENT_SUCCESS";
export const GET_PAYMENT_FAILURE = "payment/GET_PAYMENT_FAILURE";