export const LOGIN_USER = "auth/LOGIN_USER";
export const LOGIN_USER_SUCCESS = "auth/LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "auth/LOGIN_USER_FAILURE";

export const LOGOUT_USER = "auth/LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "auth/LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "auth/LOGOUT_USER_FAILURE";

export const RESET_PASSWORD = "auth/RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "auth/RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "auth/RESET_PASSWORD_FAILURE";

export const REGISTER_USER = "auth/REGISTER_USER";
export const REGISTER_USER_SUCCESS = "auth/REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "auth/REGISTER_USER_FAILURE";

export const UPDATE_PASSWORD = "auth/UPDATE_PASSWORD";
export const UPDATE_PASSWORD_SUCCESS = "auth/UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILURE = "auth/UPDATE_PASSWORD_FAILURE";
