import { queryMethods } from "../../config/apollo";

export const getUserProfileRequest = () => {
  const request = `{
      me{
          id
          first_name
          last_name
          email
          gender
          avatar
          birth_year
          street
          mobile
          certificate
          bio
          zip_code
          url
          role{
              id
              name
          }
          condition{
              id
              name
          }
          city{
              id
              name
              country{
                  id
                  name
              }
          }
          jobs{
                id
                is_completed
                price_by_hour
                total_hours
                street
                description
                the_date
                the_time
                payment_due_date
                city{
                    id
                    name
                    country{
                        id
                        name
                    }
                }
                condition{
                    id
                    name
                }
            }
          tasks{
              id
              name
              description
              image
              can_be_booked
              can_be_urgent
              accept_offer
              min_price
              created_at
              jobs{
                  id
                  is_completed
                  price_by_hour
                  total_hours
                  street
                  description
                  the_date
                  the_time
                  payment_due_date
                  city{
                      id
                      name
                      country{
                          id
                          name
                      }
                  }
                  condition{
                      id
                      name
                  }
              }
              category{
                  id
                  name
              }
              condition{
                  id
                  name
              }
          }
          created_at
          updated_at


      }
  }`;

//   console.log(request);
  return queryMethods(request);
};
