export const ADD_SERVICE = "service/ADD_SERVICE";
export const ADD_SERVICE_SUCCESS = "service/ADD_SERVICE_SUCCESS";
export const ADD_SERVICE_FAILURE = "service/ADD_SERVICE_FAILURE";

export const GET_SERVICE_LIST = "service/GET_SERVICE_LIST";
export const GET_SERVICE_LIST_SUCCESS = "service/GET_SERVICE_LIST_SUCCESS";
export const GET_SERVICE_LIST_FAILURE = "service/GET_SERVICE_LIST_FAILURE";

export const UPDATE_SERVICE = "service/UPDATE_SERVICE";
export const UPDATE_SERVICE_SUCCESS = "service/UPDATE_SERVICE_SUCCESS";
export const UPDATE_SERVICE_FAILURE = "service/UPDATE_SERVICE_FAILURE";

export const DELETE_SERVICE = "service/DELETE_SERVICE";
export const DELETE_SERVICE_SUCCESS = "service/DELETE_SERVICE_SUCCESS";
export const DELETE_SERVICE_FAILURE = "service/DELETE_SERVICE_FAILURE";

export const GET_SERVICE = "service/GET_SERVICE";
export const GET_SERVICE_SUCCESS = "service/GET_SERVICE_SUCCESS";
export const GET_SERVICE_FAILURE = "service/GET_SERVICE_FAILURE";

